openapi: 3.0.0
info:
  title: Restful Booker API
  version: "1.0"
servers:
  - url: https://restful-booker.herokuapp.com
paths:
  /auth:
    post:
      summary: Creates a new auth token
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  default: admin
                password:
                  type: string
                  default: password123
      responses:
        "200":
          description: Token created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /booking:
    get:
      summary: Returns the ids of all the bookings
      tags:
        - Booking
      parameters:
        - name: firstname
          in: query
          schema:
            type: string
        - name: lastname
          in: query
          schema:
            type: string
        - name: checkin
          in: query
          schema:
            type: string
            format: date
        - name: checkout
          in: query
          schema:
            type: string
            format: date
      responses:
        "200":
          description: An array of booking IDs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    bookingid:
                      type: number
    post:
      summary: Creates a new booking
      tags:
        - Booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Booking"
      responses:
        "200":
          description: Booking created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  bookingid:
                    type: number
                  booking:
                    $ref: "#/components/schemas/Booking"
  /booking/{id}:
    get:
      summary: Returns a specific booking based on the booking id
      tags:
        - Booking
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Detailed information of a specific booking
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking"
    put:
      summary: Updates a current booking
      tags:
        - Booking
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Booking"
      responses:
        "200":
          description: Booking updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking"
    patch:
      summary: Updates a booking with partial information
      tags:
        - Booking
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PartialBooking"
      responses:
        "200":
          description: Booking updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking"
    delete:
      summary: Deletes a booking
      tags:
        - Booking
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        "201":
          description: Booking deleted successfully
  /ping:
    get:
      summary: Health check endpoint
      tags:
        - Ping
      responses:
        "201":
          description: API is up and running

components:
  schemas:
    Booking:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        totalprice:
          type: number
        depositpaid:
          type: boolean
        bookingdates:
          type: object
          properties:
            checkin:
              type: string
              format: date
            checkout:
              type: string
              format: date
        additionalneeds:
          type: string
    PartialBooking:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        totalprice:
          type: number
        depositpaid:
          type: boolean
        bookingdates:
          type: object
          properties:
            checkin:
              type: string
              format: date
            checkout:
              type: string
              format: date
        additionalneeds:
          type: string
